# Generated by Django 2.2.4 on 2020-07-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200728_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='dish',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Dish'),
            preserve_default=False,
        ),
    ]
