# Generated by Django 2.2.4 on 2020-07-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200728_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='name', max_length=128),
            preserve_default=False,
        ),
    ]
